# Generated by Django 4.1.7 on 2023-02-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('weather_date', models.CharField(max_length=20)),
                ('maximum_temperature', models.IntegerField(blank=True, null=True)),
                ('minimum_temperature', models.IntegerField(blank=True, null=True)),
                ('precipitation', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
