# Generated by Django 4.1.7 on 2023-02-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_weather'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='precipitation',
            new_name='humidity',
        ),
    ]
