# Generated by Django 4.1.7 on 2023-02-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_precipitation_weather_humidity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='maximum_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='minimum_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
